### ISSUE TITLE
Implement alias groups by profile

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/nile#102]
Group sites by installation profile in each docroot. e.g. @sitenow @sitenow_standard, etc.

This will allow us to target sites to update in #101 

Additionally, it will provide us with aliases we can use now to manually update sites with the pending updates.

**Comment by richardbporter** [comment]
Also, I was thinking `uiowa70x.aliases.drushrc.php` with dev, test and prod aliases. These would be created per docroot. Ex. @uiowa70x.dev.

**Comment by brandonneil** [comment]
Since Rick's comment, we have determined that an alias per docroot will timeout.

I think the current discussion has been to continue going with the profile based ones, batched to a certain size.

Do we want them where they are named @custom01.dev @custom02.dev, etc where the files are named `profilexx.aliases.drushrc.php` ?

`standard01.aliases.drushrc.php`
`standard02.aliases.drushrc.php`
`standard03.aliases.drushrc.php`
`custom01.aliases.drushrc.php`
`custom02.aliases.drushrc.php`
`custom03.aliases.drushrc.php`

Or named more contextually per docroot, @uiowa701_standard01.dev @uiowa701_standard02.dev
`uiowa70x_profile_xx.aliases.drushrc.php` ?

`uiowa701_standard_01.aliases.drushrc.php`
`uiowa701_standard_02.aliases.drushrc.php`
`uiowa701_standard_03.aliases.drushrc.php`
`uiowa701_custom_01.aliases.drushrc.php`
`uiowa701_custom_02.aliases.drushrc.php`
`uiowa701_custom_03.aliases.drushrc.php`

Also, batched in 100 per group?

**Comment by richardbporter** [comment]
👍  for profilexx.aliases.drushrc.php since they're only loaded for the docroot that is currently bootstrapped.

Also, I think the groups will require _all_ aliases be generated locally, not just ones in the local manifest.

**Comment by brandonneil** [comment]
That's kind of what I was thinking too. @richardbporter I was thinking that we might create a `--all` flag to handle get all aliases vs only the local ones you have lsp'd

**Comment by brandonneil** [comment]
I thought about this more, and have made the manifest argument optional. If you do not supply a manifest url, it defaults to github.
