### ISSUE TITLE
Allow for non-www to www redirects

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/nile#103]
Engineering requires that www.somesite resolves. We are currently stripping this out in our .htaccess file. It sounds like we may have better luck by moving from htaccess re-write rules to code in our settings.php files. Our deadline to resolve this problem is approx. Oct 21.

**Comment by richardbporter** [comment]
#65

**Comment by brandonneil** [comment]
When I read #65, I didn't see this one and that as the same task. But maybe since redirection is moving to settings.php they are? I imagine we'd need something like `www:true` in the manifest, instead of adding engineering.uiowa.edu as a redirects to the upcoming redirects array:

```
redirects:
    engineering.uiowa.edu
```
?

**Comment by richardbporter** [comment]
I see what you mean.

Maybe we should just provision the sites out with www? Then the redirects array handles all cases.
