### ISSUE TITLE
Eliminate autodiscover from the logs

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/nile#121]
Currently the uiowa701 docroot's prod log stream fills with various page not found logs looking for exchange's autodiscover.xml.

https://docs.acquia.com/articles/avoiding-404-error-messages-your-logs

I sent an email to the enterprise communications team to see if this is a configuration change they can make instead of us doing something.

**Comment by richardbporter** [comment]
Hopefully, this will be handled outside of Nile. We can reopen this if not.
