### ISSUE TITLE
Allow the same domain on multiple docroots

### ISSUE THREAD

**Issue by genjohnson** [ITS-UofIowa/nile#123]
The drupal manifest is currently structured so that the domain name of each site is a key in the same array. This does not allow for us to have a site provisioned on multiple docroots using the same domain. 

This becomes an issue when a Standard site is rebuilt as a Custom site or vice versa, as we want to avoid doing a 3 card monte.

We could restructure the manifest and nile commands to add a dimension to the manifest array using the docroot identifiers.

**Comment by richardbporter** [comment]
Just to clarify this, the same domain cannot exist in multiple docroots at the same time: https://docs.acquia.com/cloud/configure/domains But this change would allow a site to be provisioned using the same URL.
