### ISSUE TITLE
Use $conf to 'fix' local site temporary file paths

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/nile#148]
$conf['file_temporary_path'] = '/tmp’;

Sql-sync's will never be the same!

(This will solve the file generation issues we have since the acquia tmp file paths dont exist locally)

**Comment by richardbporter** [comment]
We could definitely do this but that path is *nix specific and won't work on Windows. Maybe we don't care since nobody has tried Windows yet. :)

**Comment by genjohnson** [comment]
The variable `file_temporary_path` gets set to `/tmp` when `drush hloc` is run, and `drush hloc` is now run automatically when sql-syncing. So I think this issue can be closed.
