### ISSUE TITLE
Fix local uli

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/nile#149]
I thought this request was documented somewhere but cannot find it.

When running a uli on a local alias, it always fails because we don't know the dev desktop url of the site.

When you run uli with the --uri option, it works great:
``` drush @researchcoi.local uli --uri=https://coi.research.uiowa.edu.dd:8084```

nile shared:generate-aliases should add a uri value to the generated alias file so we don't have to pass that option. Also, force to SSL and the standard port.

This could save us a bunch of time.

**Comment by richardbporter** [comment]
It was covered here: https://github.com/ITS-UofIowa/nile/issues/27 

We could reopen if this is desired.

**Comment by brandonneil** [comment]
Seems like setting base_url is kind of heavy handed and would be another inconsistency with what we're doing in Acquia Cloud since we aren't setting one there.
