### ISSUE TITLE
lsp: Avoid duplicate entries in multisite list

### ISSUE THREAD

**Issue by genjohnson** [ITS-UofIowa/nile#179]
Occasionally `nile lsp` is run multiple times with the same URI, which results in the URI being listed multiple times in the Multisite list in DevDesktop. 

![screenshot 2017-10-11 15 50 15](https://user-images.githubusercontent.com/1282401/31466536-2f805a8e-ae9d-11e7-9244-aa0357cba139.png)

It'd be nice if `nile lsp` verified that the URI does not match the `name` of an item in `/Applications/DevDesktop/Acquia\ Dev\ Desktop.app/Contents/MacOS/datamodel.xml` before doing anything else. 

If an item does have a matching name, maybe output a message like `An item with that URI already exists on this docroot. Deprovision the site and then try again.`?

**Comment by richardbporter** [comment]
Ugh. That XML is no fun. Gave this a shot but might try again after break.
