### ISSUE TITLE
support subdirectory site provisioning

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/nile#21]
Handle subdirectory provisioning, like uiowa.edu/staff, housing.uiowa.edu/uhd-admin.

Namely, work around production external domains:

When the external production domain, already exists, this would generate a notice and continue gracefully. For instance, all the hawk sites, or for the housing.uiowa.edu/uhd-admin site after the housing.uiowa.edu site is provisioned.

**Comment by brandonneil** [comment]
Thinking about this some more, we probably shouldnt do anything with domains, and require that the base domain is provisioned first.

**Comment by richardbporter** [comment]
That seems logical. If DNS for example.com points to server A but we expect example.com/subsite to point at server B then we'll need some LTM iRules. 😢

**Comment by richardbporter** [comment]
Fixed in #48
