### ISSUE TITLE
Add $base_url to settings.php

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/nile#27]
Setting $base_url variable in settings.php and appending the port number will resolve the issue with drush uli opening the wrong site. _Example:_ `$base_url = 'http://cmaedu.org.uiowa.edu.dd:8083'`

**Comment by richardbporter** [comment]
This can be done in settings.local.php now that #71 is fixed.

We could do this automatically but is there any way of determining the whether a site uses HTTP/S and the port number?

**Comment by richardbporter** [comment]
I just verified that this has no impact on settings.php redirects.
