### ISSUE TITLE
local:docroot-update fails due to file permissions woes

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/nile#28]
Almost every time for me, ldu fails due to file permissions problems on settings.php. Cloning down the sitenow.uiowa.edu repo, it also failed on the theme directory.

**Comment by richardbporter** [comment]
Drupal removes write access to site folders after running updb (or cron) or something. We probably need to check and change permissions before moving anything.

**Comment by brandonneil** [comment]
I also wonder if we should change ldu from using the custom function that recursively loops through directories to just using mv or cp.

**Comment by brandonneil** [comment]
Fixed by PR #99
