### ISSUE TITLE
Invalid environment when testing an application feature branch in Acquia Cloud.

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/nile#29]
Receiving the `Invalid environment . Must be one of local, dev, test, prod, ra.` message when trying to test a pipeline start with a feature branch of an application:
`pipeline start --vcs-path=f/make-libraries --deploy-vcs-path=f/make-libraries-build`

**Comment by richardbporter** [comment]
I think we can probably drop that validation - maybe in favor of default branches for each environment?

I see it in two spots:
https://github.com/ITS-UofIowa/nile/blob/master/src/Command/Shared/GenerateSitesCommand.php#L83

https://github.com/ITS-UofIowa/nile/blob/master/src/Command/Cloud/EnvironmentBuildCommand.php#L61
