### ISSUE TITLE
Use console logger

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/nile#30]
Lessen info logging so our logs are smaller when outputted in pipeline

**Comment by richardbporter** [comment]
These logs are actually useful when debugging locally. Maybe we should look into using the logger: http://symfony.com/doc/current/components/console/logger.html

**Comment by richardbporter** [comment]
Labeled as bug since it impacts the output we get after running jobs.

**Comment by brandonneil** [comment]
No longer a bug since Acquia fixed their logging. I agree about the logging being useful.
