### ISSUE TITLE
change test env to stage

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/nile#41]

**Comment by richardbporter** [comment]
Is test required? Should we standardize on stage?

**Comment by richardbporter** [comment]
I'm wondering if this is a good idea considering all other AC references to the stage environment are 'test'. For example, the site root, ac-env, remote-user, etc. Also because developers are used to it now.

We're generating the aliases off of the default site aliases (https://cloudapi.acquia.com/#GET___me_drushrc_-instance_route). Maybe the new API will refer to it as stage?

**Comment by genjohnson** [comment]
I'm becoming a bigger and bigger fan of `stage`, especially since we have *.stage.drupal.uiowa.edu and `nile ceb stage`. 

I'd just like to use one term consistently, even if that means using `test`.

**Comment by richardbporter** [comment]
Works for me. However, the aliases provided by Acquia will still use test - those cannot be changed. For example, @uiowa701.test.

Maybe we could get some other opinions on this?

**Comment by brandonneil** [comment]
Considering that the other aliases will still be .test, I think that will be just as confusing in it's own way. I don't think it is worth the time changing it.

**Comment by joewhitsitt** [comment]
it is all muscle memory at this point for me, so unless it is across the board or seen as a big training issue going forward, i don't see the value in spending much time on it.

**Comment by richardbporter** [comment]
I agree. As of right now, we are consistent with the AC alias naming scheme. If that changes in the future, we can reopen this.
