### ISSUE TITLE
fix .org TLD naming

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/nile#68]
Sites with .org TLD's are getting provisioned with odd database, domain, alias, etc. names.

**Comment by richardbporter** [comment]
This is breaking authentication because the endpoints don't match. We need to use the same logic as the metadata-generator.

**Comment by brandonneil** [comment]
Update: #107 has the changes that have been discussed for new TLDs in a way that will not collide .org with student org sites. We will then use nile as a dependency in the metadata generator and use the Nile\Acquia\Multisite class so we consistently build the domains between the applications
