### ISSUE TITLE
improve cloud:site-provision

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/nile#70]
To do a few more things:
- [ ] open the manifest PR and insert the YAML accordingly
- [ ] merge the PR once tests pass
- [ ] build the develop -> stage -> prod environments assuming success of each one
- [ ] run a site-install for the correct profile
- [ ] sync the database and files across the environments

**Comment by richardbporter** [comment]
Blocked by #72

**Comment by genjohnson** [comment]
We're currently grouping entries in the site manifest by docroot and then ordering alphabetically. Continuing to order the entries alphabetically would complicate inserting YAML automatically. While automatically inserting YAML alphabetically probably _could_ be done, I'm not convinced it would be worth the additional work. I was originally a strong supporter of ordering entries in the manifest alphabetically but in practice have found that it's not helpful -- there are so many sites in the manifest that when looking for a particular entry I just use the search feature or `command+f`.

**Comment by genjohnson** [comment]
Blocked by #178 based on needs of the SiteNow service

**Comment by richardbporter** [comment]
I'm not sure this will happen with D8 on the horizon. Provisioning sites could be quite different then.

**Comment by richardbporter** [comment]
This is done for D8.
