### ISSUE TITLE
use settings.local.php for local overrides

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/nile#71]
I think there a few options here:

 - add the database snippets, etc. to settings.php and stop creating this file
 - add the database snippets, etc. to settings.php and create settings.local.php as a blank file that developers could use to override settings locally, e.g. $conf['theme_debug'] = TRUE;
- add the database snippets, etc. to settings.php and create settings.local.php with all local overrides set already

**Comment by brandonneil** [comment]
I like "add the database snippets, etc. to settings.php and create settings.local.php as a blank file that developers could use to override settings locally, e.g. $conf['theme_debug'] = TRUE;"

This would just get created on developer machines.

**Comment by richardbporter** [comment]
I think this is blocked by #57
