### ISSUE TITLE
Add --all option for cloud:environment-build

### ISSUE THREAD

**Issue by genjohnson** [ITS-UofIowa/nile#73]
It would be helpful (especially for the current workflow of setting up new Standard sites) to have an option that would build all environments (dev, stage, prod) with one command. I'm thinking this could be`nile cloud:environment-build --all`

**Comment by richardbporter** [comment]
This one scares me a little bit. if #70 was completed, do you think this option would still be useful/required?

**Comment by genjohnson** [comment]
@richardbporter if #70 was completed then the `nile ceb --all` option would no longer be useful for setting up new Standard sites. If #70 is the direction we're planning to go, then I would close this issue.

**Comment by richardbporter** [comment]
I agree, thanks!
