### ISSUE TITLE
Implement task automation for sites

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/nile#89]
Perhaps via a .tasks.yml file for something.

**Comment by brandonneil** [comment]
We should run a default set of tasks on all sites that are updated, like updb.

Then, .tasks.yml tasks. Do we need to consider .tasks.yml overriding the default set of tasks? Adam mentioned he didn't want to run updb.

**Comment by richardbporter** [comment]
Related: https://github.com/ITS-UofIowa/herky/issues/26
